"""Shared integer-second time units and generic diary defaults."""

from typing import Final

SECONDS_PER_MINUTE: Final[int] = 60
SECONDS_PER_HOUR: Final[int] = 60 * SECONDS_PER_MINUTE
SECONDS_PER_DAY: Final[int] = 24 * SECONDS_PER_HOUR
DEFAULT_TIME_ORIGIN_CLOCK: Final[str] = "00:00"
DEFAULT_OBSERVATION_WINDOW_SECONDS: Final[int] = SECONDS_PER_DAY
DEFAULT_SEQUENCE_INTERVAL_SECONDS: Final[int] = 15 * SECONDS_PER_MINUTE
DEFAULT_MIN_ACTIVITY_DURATION_SECONDS: Final[int] = 30 * SECONDS_PER_MINUTE

__all__: Final[tuple[str, ...]] = (
    "DEFAULT_MIN_ACTIVITY_DURATION_SECONDS",
    "DEFAULT_OBSERVATION_WINDOW_SECONDS",
    "DEFAULT_SEQUENCE_INTERVAL_SECONDS",
    "DEFAULT_TIME_ORIGIN_CLOCK",
    "SECONDS_PER_DAY",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_MINUTE",
)
